name: CI Checks

on:
  push:
    branches: [main, develop, feature/*]
  pull_request:
    branches: [main, develop]

jobs:
  healthcheck:
    runs-on: ubuntu-latest
    env:
      REPO_PATH: ${{ github.workspace }} # Path to the repository
      CI: true # This is a workaround to skip the internet connection check in CI
    steps:
      - uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils

      - name: Healthcheck environment
        run: |
          sudo chmod +x $REPO_PATH/scripts/healthcheck_environment.sh
          sudo $REPO_PATH/scripts/healthcheck_environment.sh
