name: CI Checks

on:
  push:
    branches: [main, develop, feature/*]
  pull_request:
    branches: [main, develop]

env:
  CI: "true"
  REPO_PATH: ${{ github.workspace }} # Path to the repository

jobs:
  healthcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils

      - name: Healthcheck environment
        run: |
          sudo chmod +x $REPO_PATH/scripts/healthcheck_environment.sh
          # Use sudo -E to preserve the CI environment variable
          sudo -E $REPO_PATH/scripts/healthcheck_environment.sh
